# Generated by Django 4.2.7 on 2024-06-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movie_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cfav',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
