# Generated by Django 4.2.7 on 2024-06-11 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_favorite_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 11, 5, 26, 42, 221395, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
